language: node_js
node_js:
- '5.1'
before_deploy:
- git config user.email "njenan@gmail.com"
- git config user.name "Travis CI"
- npm run package
deploy:
  provider: npm
  email: njenan@gmail.com
  api_key:
    secure: Bz9xy8inT6gq2eMdzR2vsjpCdFPQB+ZXamBHGY+fonZABGZRLXb9RsJDWOIVp9HojBPokVd5NBkKqdkNZRLCikJj0M7O6zUkm8AP+UTlfeY/gs+81CKEkFQAhhoJGdlockVBeqXO3h9wgH+FoHDQ10/o8Ugrig0BjT7BNmswCPiQQOySN6WG3Fk8pE84B76kyWaBhJMIvmmAFVXafuFtPt2/qjb4rHr5S51rwLEgS+HSIy3IXYHRBXnht50QHfS905Ey/pDxbuyQvE6slg7XrJAcY6gEmKIiFkxHt9iS02SpX3ifMFrFO/NYQd4kBEdEQSbTE4UESLizyw0Gs0xhNwTDEHFSbtsW0JNxlqGngt+wZpqvxeqozLT6HRIq0IAH3UplRV5Uz5pbSNgt0b5pUoq+ihu5zSS36VcInvCgi93H8TVZWNs1nxrFhTHqlHIU2B4LSiHmjHgdHSzi2gyt/QBkd60mPq8WoqK3rJuYfVhYrOLMvBl7Fm7tT69wQ1BHE34icufCD6K9/UN3L1yGaEySSlBOrp8du0kPeeJH/NPzWk4bWAkQlNnS8XXZ2pNISmJyPUQ1oriHx7siBUkHn9vU96txdOiMHi2GwMsDAQf2OmHkKfHYKWyJf7pDespGPoGIXUWaTjLiKhAfA6EfaV7AjbQbDwCWeCI35gj8vmc=
  on:
    tags: true
    repo: njenan/turbulence
script:
  - npm run all